source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'App', :exclusive => true do
  pod "XExtensionItem", :path => "../"
end

target 'Extension', :exclusive => true do
  pod "XExtensionItem", :path => "../"
end
