source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'XExtensionItem', :exclusive => true do
  pod "XExtensionItem", :path => "../"
end

target 'ShareExtension', :exclusive => true do
  pod "XExtensionItem", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "XExtensionItem", :path => "../"
end
